### ISSUE TITLE
Please update compiler feature support matrix for VS2017

### ISSUE THREAD

**Issue by leeter** [Microsoft/cpp-docs#11]
https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/support-for-cpp11-14-17-features-modern-cpp.md only references up to vs2015

**Comment by corob-msft** [comment]
This material has been updated and consolidated with the [Visual C++ Language Conformance](https://docs.microsoft.com/en-us/cpp/visual-cpp-language-conformance) topic, so that we don't have ever-expanding tables and a lengthening discussion of obsolete bugs cluttering the feature lists. The current page should automatically redirect you to the new page.
